### ISSUE TITLE
Error upon launch

### ISSUE THREAD

**Issue by Pawlakov** [carykh/recordTrimEdit#12]
Running on Windows
> Traceback (most recent call last):
>   File "C:\Users\Pawlakov\Desktop\Informatyka\Repozytoria\recordTrimEdit\recordTrimEdit.py", line 303, in <module>
>     drawWaveforms(screen)
>   File "C:\Users\Pawlakov\Desktop\Informatyka\Repozytoria\recordTrimEdit\recordTrimEdit.py", line 162, in drawWaveforms
>     audio_array.reshape((882))
> ValueError: cannot reshape array of size 1764 into shape (882,)

**Comment by ben9583** [comment]
This issue is already being documented in #6, so I'll close this for now.

**Comment by ben9583** [comment]
If you have any other details about your setup you wanna include, please do so there.
