### ISSUE TITLE
No license found

### ISSUE THREAD

**Issue by JacksonChen666** [carykh/recordTrimEdit#2]
This project does not seem to have a license declared in an obvious way, or at all. A license should be added (as this project seems to be intended as open source) so that users can run, modify, study, distribute, and use the code.

https://choosealicense.com/no-permission/

**Comment by Drogobo** [comment]
I would recommend the GPLv3, or X11 license.

**Comment by izzy** [comment]
Given that this references [pygame](https://github.com/pygame/pygame/blob/main/examples/audiocapture.py) as a source, which in itself [uses LGPL-2.1-or-later](https://github.com/pygame/pygame/blob/main/docs/LGPL.txt), there's not a lot of room for what license this repo actually *could* be.

**Comment by ben9583** [comment]
Since I'm not the copyright holder I'll defer working on this issue unless Cary gives input

**Comment by ThatOneCalculator** [comment]
+1 on expediting this. It's often impossible to package code for redistribution on package managers without a license

**Comment by ben9583** [comment]
> Given that this references [pygame](https://github.com/pygame/pygame/blob/main/examples/audiocapture.py) as a source, which in itself [uses LGPL-2.1-or-later](https://github.com/pygame/pygame/blob/main/docs/LGPL.txt), there's not a lot of room for what license this repo actually _could_ be.

This is not true. You only need to do this if you modify pygame itself, otherwise you just need to include the source code.

**Comment by izzy** [comment]
> > Given that this references [pygame](https://github.com/pygame/pygame/blob/main/examples/audiocapture.py) as a source, which in itself [uses LGPL-2.1-or-later](https://github.com/pygame/pygame/blob/main/docs/LGPL.txt), there's not a lot of room for what license this repo actually _could_ be.
> 
> This is not true. You only need to do this if you modify pygame itself, otherwise you just need to include the source code of pygame.

Please have a look at the referenced source that's mentioned in the first line of the code:

```py
# Source: https://github.com/pygame/pygame/blob/main/examples/audiocapture.py
```

If you diff it it's somewhat obvious cary used this as a basis and while there's not much left, there's still whole chunks from the original that are in the code verbatim. 

So this seems to very likely be a (heavily) modified version of parts of the source of pygame and as such would need to use the aforementioned license(or a compatible one).

**Comment by ben9583** [comment]
> If you diff it it's somewhat obvious cary used this as a basis and while there's not much left, there's still whole chunks from the original that are in the code verbatim.

The examples [are in the public domain.](https://github.com/pygame/pygame/blob/main/examples/README.rst)

**Comment by carykh** [comment]
I added an MIT license! It's the most free option, since I want other people to be able to toy around and modify my code freely, as long as they acknowledge that i'm the original owner
