### ISSUE TITLE
Wont run

### ISSUE THREAD

**Issue by mdbeach** [carykh/recordTrimEdit#3]
literally just wont run
heres what pops up

D:\github\recordTrimEdit>python recordTrimEdit.py
pygame 2.5.2 (SDL 2.28.3, Python 3.10.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\github\recordTrimEdit\recordTrimEdit.py", line 188, in <module>
    for event in pg.event.get():
SystemError: <built-in function get> returned a result with an exception set

**Comment by ben9583** [comment]
Hmm no idea what would cause this; can you tell me a bit more about your hardware and software setup?

**Comment by ben9583** [comment]
Closing this as stale.
